### PR TITLE
raise error in dep.py if fortran preprocessor fails

### PR DESCRIPTION
**Pull request by nbren12**
Fixes https://github.com/BoxLib-Codes/BoxLib/issues/15

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
We cannot use bash.

**Comment by zingale** [comment]
yeah.  This is a cute solution, but not everyone will be using bash.

I think I can do this in python via subprocess.

It also may just be that we don't need the `cat` part at all -- the C++ build stuff never seems to do anything but `cat` there, so I am not sure what the use case was for this postprocessing originally.

Maybe we can just ditch it?

Otherwise, we can come up with a python solution to this.

**Comment by nbren12** [comment]
:( oh well. My function is wrong also. `[[ $? ]]` should be`[[ $? -eq 0 ]]`.

**Comment by WeiqunZhang** [comment]
Let's ditch cat.  It's certainly not needed now.  If needed in the future,
we will find a way.

But do this after git merge day tomorrow.

**Comment by nbren12** [comment]
ok. i removed the bash stuff. the error code checking stuff is still relevant I guess.

**Comment by WeiqunZhang** [comment]
Can we use the same technique in the following commit to pass the error
message back to make?

https://github.com/BoxLib-Codes/BoxLib/commit/67b3f9c93eaa1f49983a07078518b89429a4e143


Weiqun

**Comment by WeiqunZhang** [comment]
Maybe we should squash and merge this.  Then in `doit`, catch the error and output error to stdout.

**Pull request merged**
